<?php

/**
 * @file
 * Handles tierce functions for pd_core.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pd_core_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'pd_core_user_login_form_submit';
}

/**
 * Custom submit handler for the login form.
 */
function pd_core_user_login_form_submit($form, FormStateInterface $form_state) {
  $config = \Drupal::config('pd_core.settings');
  $user = User::load(\Drupal::currentUser()->id());
  $messenger = \Drupal::messenger();
  
  if ($user->hasRole('vendor')) {
    $messenger->addStatus(Markup::create($config->get('vendor_message')['value']));
  }

  if ($user->hasRole('employee')) {
    $messenger->addStatus(Markup::create($config->get('employee_message')['value']));
  }
}