definitions:
  user__page:
    menu_name: backoffice
    parent: ''
    weight: -50
    expanded: false
    enabled: true
  user__logout:
    weight: -49
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
