module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  better_normalizers: 0
  block: 0
  block_class: 0
  bootstrap_paragraphs: 0
  breakpoint: 0
  context: 0
  context_ui: 0
  contextual: 0
  ctools: 0
  dblog: 0
  default_content: 0
  default_content_deploy: 0
  devel: 0
  devel_php: 0
  dynamic_page_cache: 0
  eck: 0
  email_registration: 0
  entity: 0
  entity_class: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  fpa: 0
  front_page: 0
  hal: 0
  hierarchical_term_formatter: 0
  image: 0
  inline_entity_form: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  maillog: 0
  markup: 0
  menu_link_content: 0
  menu_link_content_visibility: 0
  menu_token: 0
  menu_ui: 0
  multiple_registration: 0
  node: 0
  nodejs: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pd_coverage: 0
  pd_request: 0
  pd_vendor: 0
  profile: 0
  quickedit: 0
  realname: 0
  redirect: 0
  redirect_after_login: 0
  serialization: 0
  shs: 0
  stage_file_proxy: 0
  system: 0
  taxonomy: 0
  term_csv_export_import: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_show_more: 0
  views_ui: 0
  viewsreference: 0
  workflow: 0
  workflow_ui: 0
  xeno_hero: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  bootstrap_barrio: 0
  pendeedus: 0
  stable: 0
  classy: 0
  seven: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
