service_key: __FIXME__
log_http_errors: true
auth_get_token_callback: nodejs_auth_get_token_callback
auth_check_callback: nodejs_auth_check_callback
enable_userchannel: true
pages: '*'
authenticated_users_only: false
nodejs:
  scheme: http
  host: localhost
  port: 8080
client:
  scheme: http
  host: localhost
  port: 8080
socket_io:
  path: 'http://localhost:8080/socket.io/socket.io.js'
  type: external
_core:
  default_config_hash: _QO2D-6NK1XTO_QRQen8lqwC5SdH3xpA6YgHx4E3UZI
